name: RogueLonk
version: '${project.version}'
main: org.Lonk.RogueLonk
api-version: '1.20'
authors: [Lonk]
description: A quick and easy way to make roguelikes
commands:
  RLP:
    description: Main command for RogueLonk
    usage: /RLP <subcommand> [args]

  giveitem:
    description: Gives a custom item to the player
